version: '3.8'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'python manage.py runserver 0.0.0.0:8000' # run command after build. works same if it was in Dockerfile as CMD command
        ports: 
            - 8000:8000
        volumes: 
            - .:/app # All the files in the path are connected with the docker container. Any change that happens in the path will be reflected in the docker file and vice versa
        depends_on: 
            - db # means <db> container should run first before our <backend> container

    
            
    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'python consumer.py' # run command automatically instead of doing it manually
        depends_on: 
            - db



    db: 
        image: mysql:5.7.22
        restart: always # sometymes  mysql stops and this will stop the docker container affecting our app
        environment: 
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - .dbdata:/var/lib/mysql # when mysql stores data, we need it to map the data to a folder(.dbdata)
        ports:
            - 33066:3306 # port is not needed, only use to see the data from outside